apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ai-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/bilalgu/k8s-ai-bootstrap'
    targetRevision: main
    path: k8s/base
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: ai-app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
