apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ai-api-role
  namespace: ai-app
rules:
  - apiGroups: [""]
    resources: ["pods", "services"]
    verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ai-api-rolebinding
  namespace: ai-app
subjects:
  - kind: User
    name: bilal
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: ai-api-role
  apiGroup: rbac.authorization.k8s.io