apiVersion: v1
kind: Service
metadata:
  name: ai-api-service
  namespace: ai-app
spec:
  selector:
    app: ai-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: ClusterIP