apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: promtail
  namespace: observability
spec:
  selector:
    matchLabels:
      app: promtail
  template:
    metadata:
      labels:
        app: promtail
    spec:
      containers:
        - name: promtail
          image: grafana/promtail
          args:
            - -config.file=/etc/promtail/config.yaml
          volumeMounts:
            - name: varlog
              mountPath: /var/log
            - name: promtail-config  
              mountPath: /etc/promtail
      volumes:
        - name: varlog
          hostPath:
            path: /var/log
        - name: promtail-config
          configMap:
            name: promtail-config

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: promtail-config
  namespace: observability
data:
  config.yaml: |
    server:
      http_listen_port: 9080
      grpc_listen_port: 0

    positions:
      filename: /tmp/positions.yaml

    clients:
      - url: http://loki.observability.svc.cluster.local:3100/loki/api/v1/push

    scrape_configs:
      - job_name: system
        static_configs:
          - targets:
            - localhost
            labels:
              job: varlogs
              __path__: /var/log/*log